### ISSUE TITLE
Just question

### ISSUE THREAD

**Issue by dkosasih** [beeman/angular-presentations#1]
Hello Beeman, 

Just curious on why is this project stop? 
I had a similar idea, I just want to find out why you have in mind before I decide whether I am attempting to do it or throw the idea away. 

Thanks
dK

**Comment by beeman** [comment]
Hey dK, basically lack of time and interest. I decided to use an existing tool (spectacle) for my presentations and did not continue working on this project.

**Comment by dkosasih** [comment]
That's s what I have in mind, Angular version of Spectacle.

Thanks for the prompt reply 😊
